import type { Event } from '../types/event'

export const MOCK_EVENTS: Event[] = [
  {
    id: 'mock1',
    title: 'Moderat — Live in Athens',
    date: '2026-05-16T21:00:00',
    venue: 'Gagarin 205',
    location: 'Kypseli',
    category: 'electronic',
    description: 'Moderat returns to Athens for a breathtaking live performance of their latest album. Expect cinematic soundscapes, powerful visuals and an unforgettable night of electronic music.',
    image_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&h=340&fit=crop',
    ticket_url: 'https://www.viva.gr',
    ticket_source: 'viva',
    price: '€35',
    artists: ['Moderat'],
  },
  {
    id: 'mock2',
    title: 'Peggy Gou DJ Set',
    date: '2026-05-17T23:00:00',
    venue: 'Venue Athens',
    location: 'Gazi',
    category: 'dj',
    description: 'South Korean DJ and producer Peggy Gou brings her signature blend of house and electronic music to Venue Athens for one of the most anticipated DJ sets of the summer.',
    image_url: 'https://images.unsplash.com/photo-1571266028243-d220c6a86493?w=600&h=340&fit=crop',
    ticket_url: 'https://www.residentadvisor.net',
    ticket_source: 'ra',
    price: '€25',
    artists: ['Peggy Gou'],
  },
  {
    id: 'mock3',
    title: 'Summer Closing Party',
    date: '2026-05-18T22:00:00',
    venue: 'Six D.O.G.S',
    location: 'Monastiraki',
    category: 'party',
    description: 'The legendary Six D.O.G.S summer closing party with three floors of music, outdoor garden, and a lineup of local and international DJs spinning from sunset to sunrise.',
    image_url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&h=340&fit=crop',
    ticket_url: 'https://www.ticketswap.com',
    ticket_source: 'ticketswap',
    price: 'Free',
    artists: ['Local DJs'],
  },
  {
    id: 'mock4',
    title: 'Nick Cave & The Bad Seeds',
    date: '2026-05-20T20:30:00',
    venue: 'Fuzz Live',
    location: 'Tavros',
    category: 'concert',
    description: 'Nick Cave & The Bad Seeds perform a career-spanning set in Athens as part of their European tour. One of the most powerful live acts in the world, not to be missed.',
    image_url: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&h=340&fit=crop',
    ticket_url: 'https://www.viva.gr',
    ticket_source: 'viva',
    price: '€45',
    artists: ['Nick Cave', 'The Bad Seeds'],
  },
  {
    id: 'mock5',
    title: 'Aphex Twin — Electronic Night',
    date: '2026-05-22T22:00:00',
    venue: 'Technopolis',
    location: 'Gazi',
    category: 'electronic',
    description: 'A rare Aphex Twin appearance at the iconic Technopolis venue. Expect mind-bending IDM and experimental electronic music in one of Athens\' most atmospheric outdoor spaces.',
    image_url: 'https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=600&h=340&fit=crop',
    ticket_url: 'https://www.ticketmaster.gr',
    ticket_source: 'ticketmaster',
    price: '€40',
    artists: ['Aphex Twin'],
  },
  {
    id: 'mock6',
    title: 'Athens Jazz Festival',
    date: '2026-05-24T19:00:00',
    venue: 'Stavros Niarchos Foundation',
    location: 'Kallithea',
    category: 'concert',
    description: 'The annual Athens Jazz Festival returns with a stellar lineup of international and Greek jazz artists. Three days of music in the stunning surroundings of the Stavros Niarchos Foundation Cultural Center.',
    image_url: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&h=340&fit=crop',
    ticket_url: 'https://www.more.com.gr',
    ticket_source: 'other',
    price: '€20',
    artists: ['Various Artists'],
  },
]
